version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: op_codigo_de_ouro_production
    ports:
      - "5432:5432"
  app:
    build: .
    env_file:
      - .env
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/op_codigo_de_ouro
    ports:
      - "80:3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/op_codigo_de_ouro_production
    depends_on:
      - db